apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-controller
spec:
  template:
    spec:
      containers:
        - name: object-controller
          env:
            - name: OAAS_OC_S3PREFIXURL
              value: http://s3.10.131.36.27.nip.io/${BUCKET_NAME}
#              value: http://10.43.187.186/${BUCKET_NAME}
