
"%dev":
  quarkus:
    http:
      port: 8090

objectControllerUrl: http://localhost:8088

quarkus:
  http:
    access-log:
      enabled: true
  vertx:
    prefer-native-transport: true
#  index-dependency:
#    service-interface:
#      artifact-id: service-interface
#      group-id: org.hpcclab.msc
  console:
    color: true
  container-image:
    image: ${ci.registry.image:oaas}/stream-controller${tag:}
  jib:
    base-jvm-image: adoptopenjdk/openjdk16:ubi-minimal-jre

#mp:
#  messaging:
#    outgoing:
#      tasks:
#        connector: smallrye-kafka
#        topic: msc-tasks
#        value:
#          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
#    incoming:
#      resource-requests:
#        connector: smallrye-kafka
#        topic: msc-resource-requests
#        auto:
#          offset:
#            reset: earliest
