
"%dev":
  quarkus:
    http:
      port: 8090

objectControllerUrl: http://localhost:8088


quarkus:
  http:
    access-log:
      enabled: true
  vertx:
    prefer-native-transport: true
  console:
    color: true
  container-image:
    image: ${ci.registry.image:oaas}/stream-controller${tag:}
  jib:
    base-jvm-image: adoptopenjdk/openjdk16:ubi-minimal-jre
  kafka-streams:
    bootstrap-servers: localhost:9092
    application-server: ${hostname}:8080
    topics: request, distinct-request

