apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: oaas
spec:
  kafka:
    replicas: 1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    resources:
#      limits:
#        cpu: 2
#        memory: 1G
#      requests:
#        cpu: 0.5
#        memory: 0.5G
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: '3.2'
      inter.broker.protocol.version: '3.2'
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 1Gi
      deleteClaim: true
    resources:
      requests:
        cpu: 0.5
        memory: 128M
  entityOperator:
    topicOperator: {}
#    userOperator: {}
#  cruiseControl: {}
