# Use postgres/example user/password credentials
version: '3.1'

services:

  infinispan:
    image: quay.io/infinispan/server
    restart: always
    ports:
      - "11222:11222"
    environment:
      USER: oaas
      PASS: oaas

  oc:
    depends_on:
      - redpanda
      - infinispan
    build:
      context: object-controller
      dockerfile: src/main/docker/Dockerfile.jvm
    restart: always
    ports:
      - "8088:8080"
    environment:
      QUARKUS_CONSOLE_COLOR: 'false'
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://redpanda:9092
      OAAS_OC_TASKGENERATORURL: http://task-manager
      OAAS_OC_PROVISIONTOPIC: msc-provisions
      OAAS_SA_S3PREFIXURL: http://s3.10.131.36.27.nip.io/test
      INFINISPAN_SERVER: infinispan:11222
      INFINISPAN_USERNAME: oaas
      INFINISPAN_PASSWORD: oaas
#      OAAS_REPO_OBJECT_PERSIST: 'false'
#      OAAS_REPO_STATE_PERSIST: 'false'
#      OAAS_REPO_COMPLETION_PERSIST: 'false'

  tm:
    restart: always
    depends_on:
      - redpanda
      - infinispan
    build:
      context: task-manager
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8090:8080"
    environment:
      QUARKUS_CONSOLE_COLOR: 'false'
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://redpanda:9092
      OAAS_SA_S3PREFIXURL: http://s3.10.131.36.27.nip.io/test
      INFINISPAN_SERVER: infinispan:11222
      INFINISPAN_USERNAME: oaas
      INFINISPAN_PASSWORD: oaas
      OAAS_TM_OBJECTCONTROLLERURL: http://oc:8080
      OAAS_TM_BROKERURL: http://localhost:8080/msc/default
      OAAS_TM_TASKCOMPLETIONTOPIC: msc-task-completions
      OAAS_TM_TASKCOMPLETIONPARTITIONS: '1'
#      OAAS_REPO_OBJECT_PERSIST: 'false'
#      OAAS_REPO_STATE_PERSIST: 'false'
#      OAAS_REPO_COMPLETION_PERSIST: 'false'

  redpanda:
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://redpanda:9092
    # NOTE: Please use the latest version here!
    image: docker.vectorized.io/vectorized/redpanda:v21.10.2
    container_name: redpanda-1
    ports:
      - 9092:9092
      - 29092:29092
