apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: durable-transcode-func
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "3"
    spec:
      containerConcurrency: 1
      containers:
        - image: core.harbor.10.131.36.27.nip.io/oaas/evaluation-knative:0.3.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: '1'

---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: durable-transcode-func-trigger
  annotations:
    knative-eventing-injection: enabled
spec:
  broker: default
  filter:
    attributes:
      kafkaheadercetype: oaas.task
      kafkaheadercefunction: builtin.video.transcode-durable
      kafkaheadercetasktype: DURABLE
  subscriber:
    ref:
      apiVersion: flows.knative.dev/v1
      kind: Sequence
      name: durable-transcode-func-sq
---
apiVersion: flows.knative.dev/v1
kind: Sequence
metadata:
  name: durable-transcode-func-sq
spec:
  channelTemplate:
    apiVersion: messaging.knative.dev/v1
    kind: InMemoryChannel
  steps:
    - ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: durable-transcode-func
      delivery:
        deadLetterSink:
          ref:
            apiVersion: v1
            kind: Service
            name: job-provisioner
  reply:
    ref:
      apiVersion: v1
      kind: Service
      name: job-provisioner

