"%dev":
  quarkus:
    http:
      port: 8090
  oaas:
    log: DEBUG


oaas:
  log: INFO


quarkus:
  http:
    access-log:
      enabled: true
      pattern: '"%r" %s %b %{RESPONSE_TIME} ms'
      exclude-pattern: /q/.*
    record-request-start-time: true
  log:
    category:
      "org.hpcclab.oaas":
        level: ${oaas.log}
  vertx:
    prefer-native-transport: true
    worker-pool-size: 100
  swagger-ui:
    always-include: true
  smallrye-openapi:
    store-schema-directory: ../doc/tm
  console:
    color: true
  container-image:
    image: ${ci.registry.image:oaas}/task-manager${tag:}
  jib:
    base-jvm-image: eclipse-temurin:17-jre-ubi9-minimal
  micrometer:
    export:
      json:
        enabled: true
        path: jsonmetrics
  rest-client:
    RemoteInvocationHandler:
      url: ${oaas.tm.invokerUrl}
      connection-pool-size: ${oaas.tm.connectionPoolMaxSize}
      http2: true


mp:
  messaging:
    outgoing:
      tasks:
#        enabled: ${oaas.tm.kafkaEnabled}
        connector: smallrye-kafka
        topic: ${oaas.tm.taskTopic}
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
        merge: true
