apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: msc-schema-registry
  name: msc-schema-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msc-schema-registry
  template:
    metadata:
      labels:
        app: msc-schema-registry
    spec:
      enableServiceLinks: false
      containers:
        - name: msc-schema-registry
          env:
            - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
              value: 'PLAINTEXT://msc-kafka-bootstrap:9092'
            - name: SCHEMA_REGISTRY_HOST_NAME
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: SCHEMA_REGISTRY_LISTENERS
              value: http://0.0.0.0:8081
            - name: SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL
              value: PLAINTEXT
          image: confluentinc/cp-schema-registry:6.2.0
#          image: core.harbor.10.131.36.27.nip.io/proxy/confluentinc/cp-schema-registry:6.2.0
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: msc-schema-registry
  name: msc-schema-registry
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 8081
  selector:
    app: msc-schema-registry
