"%test":
  oaas:
    sa:
      s3:
        accessKey: accessKey
        secretKey: secretKey
        url: http://s3.test.com
        publicUrl: http://s3.test.com

#"%prod":
#  quarkus:
#    infinispan-client:
#      auth-username: ${infinispan.username:}
#      auth-password: ${infinispan.password:}
#      server-list: ${infinispan.server:}

"%dev":
  oaas:
    log: DEBUG
  quarkus:
    http:
      port: 8093
    console:
      color: true

oaas:
  log: INFO

quarkus:
  minio:
    allow-empty: true
  http:
    access-log:
      enabled: true
      pattern: '"%r" %s %b %{RESPONSE_TIME} ms'
      exclude-pattern: /q/.*
    record-request-start-time: true
  vertx:
    prefer-native-transport: true
  container-image:
    image: ${ci.registry.image:oaas}/storage-adapter${tag:}
  jib:
    base-jvm-image: eclipse-temurin:17-jre-ubi9-minimal
  opentelemetry:
    enabled: false
  log:
    category:
      "org.hpcclab.oaas":
        level: ${oaas.log}
