"%test":
  oaas:
    sa:
      s3:
        accessKey: accessKey
        secretKey: secretKey
        url: http://s3.test.com
        publicUrl: http://s3.test.com
"%prod":
  quarkus:
    infinispan-client:
      auth-username: ${infinispan.username:}
      auth-password: ${infinispan.password:}
      server-list: ${infinispan.server:}
  repo:
    createOnStart: true
    object:
      persist: true
    state:
      persist: true
    completion:
      persist: true

"%dev":
  quarkus:
    http:
      port: 8093
    log:
      category:
        "org.hpcclab.oaas":
          level: DEBUG
    console:
      color: true

quarkus:
  minio:
    allow-empty: true
  http:
    access-log:
      enabled: true
      pattern: '"%r" %s %b %{RESPONSE_TIME} ms'
      exclude-pattern: /q/.*
    record-request-start-time: true
  vertx:
    prefer-native-transport: true
  container-image:
    image: ${ci.registry.image:oaas}/storage-adapter${tag:}
  jib:
    base-jvm-image: eclipse-temurin:17-jre-alpine
  native:
    builder-image: quay.io/quarkus/ubi-quarkus-mandrel:22.2-java17
  log:
    category:
      "org.hpcclab.oaas":
        level: ${oaas.log:INFO}
  index-dependency:
    repository:
      artifact-id: repository
      group-id: org.hpcclab.oaas
    model:
      artifact-id: model
      group-id: org.hpcclab.oaas
  opentelemetry:
    enabled: false
