apiVersion: apps/v1
kind: Deployment
metadata:
  name: stream-controller
  labels:
    app: stream-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-controller
  template:
    metadata:
      labels:
        app: stream-controller
    spec:
      containers:
        - name: stream-controller
          envFrom:
            - configMapRef:
                name: oaas-env
          image: registry.gitlab.com/multimedia-streaming-cloud-ecosystem/msc-oaas/stream-controller:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512M
            requests:
              cpu: 500m
              memory: 256M
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: stream-controller
spec:
  selector:
    app: stream-controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
