---
openapi: 3.0.3
info:
  title: task-manager API
  version: 0.2.0-SNAPSHOT
paths:
  /api/resource-requests:
    post:
      tags:
      - Resource Request Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectResourceRequest'
      responses:
        "201":
          description: Created
  /api/task-completions:
    get:
      tags:
      - Task Completion Resource
      responses:
        "200":
          description: OK
          content:
            text/event-stream:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UUID'
  /api/task-exec:
    post:
      tags:
      - Task Exec Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskExecRequest'
      responses:
        "201":
          description: Created
components:
  schemas:
    OaasObjectOrigin:
      type: object
      properties:
        additionalInputs:
          type: array
          items:
            format: uuid
            pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
            type: string
        args:
          type: object
          additionalProperties:
            type: string
        funcName:
          type: string
        parentId:
          $ref: '#/components/schemas/UUID'
        rootId:
          $ref: '#/components/schemas/UUID'
    ObjectResourceRequest:
      type: object
      properties:
        ownerObjectId:
          type: string
        requestFile:
          type: string
    TaskExecRequest:
      type: object
      properties:
        id:
          type: string
        originList:
          type: array
          items:
            type: object
            additionalProperties:
              $ref: '#/components/schemas/OaasObjectOrigin'
    UUID:
      format: uuid
      pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
      type: string
