---
openapi: 3.0.3
info:
  title: task-manager API
  version: 0.2.0-SNAPSHOT
paths:
  /api/task-completions:
    post:
      tags:
      - Task Completion Consumer
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/TaskCompletion'
      responses:
        "201":
          description: Created
  /oal:
    post:
      tags:
      - Oal Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectAccessLangauge'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasObject'
  /oal/-/{filePath}:
    post:
      tags:
      - Oal Resource
      parameters:
      - name: filePath
        in: path
        required: true
        schema:
          pattern: .*
          type: string
      - name: await
        in: query
        schema:
          type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectAccessLangauge'
      responses:
        "200":
          description: OK
          content:
            application/json: {}
  /oal/{oal}:
    get:
      tags:
      - Oal Resource
      parameters:
      - name: oal
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasObject'
  /oal/{oal}/{filePath}:
    get:
      tags:
      - Oal Resource
      parameters:
      - name: filePath
        in: path
        required: true
        schema:
          pattern: .*
          type: string
      - name: oal
        in: path
        required: true
        schema:
          type: string
      - name: await
        in: query
        schema:
          type: boolean
      responses:
        "200":
          description: OK
          content:
            application/json: {}
components:
  schemas:
    OaasObject:
      type: object
      properties:
        cls:
          type: string
        embeddedRecord:
          type: string
        id:
          type: string
        labels:
          uniqueItems: true
          type: array
          items:
            type: string
        origin:
          $ref: '#/components/schemas/ObjectOrigin'
        originHash:
          format: int64
          type: integer
        refs:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/ObjectReference'
        state:
          $ref: '#/components/schemas/OaasObjectState'
        status:
          $ref: '#/components/schemas/ObjectStatus'
        streamInfo:
          $ref: '#/components/schemas/StreamInfo'
    OaasObjectState:
      type: object
      properties:
        overrideUrls:
          type: object
          additionalProperties:
            type: string
        stateId:
          type: string
        type:
          $ref: '#/components/schemas/StateType'
    ObjectAccessLangauge:
      type: object
      properties:
        args:
          type: object
          additionalProperties:
            type: string
        functionName:
          type: string
        inputs:
          type: array
          items:
            type: string
        target:
          type: string
    ObjectOrigin:
      type: object
      properties:
        args:
          type: object
          additionalProperties:
            type: string
        funcName:
          type: string
        inputs:
          type: array
          items:
            type: string
        parentId:
          type: string
        wfi:
          type: boolean
    ObjectReference:
      type: object
      properties:
        name:
          type: string
        objId:
          type: string
    ObjectStatus:
      type: object
      properties:
        completionTime:
          format: int64
          type: integer
        createdTime:
          format: int64
          type: integer
        debugLog:
          type: string
        submittedTime:
          format: int64
          type: integer
        taskStatus:
          $ref: '#/components/schemas/TaskStatus'
        waitFor:
          type: array
          items:
            type: string
    StateType:
      enum:
      - COLLECTION
      - FILES
      type: string
    StreamInfo:
      type: object
      properties:
        count:
          format: int32
          type: integer
    TaskCompletion:
      type: object
      properties:
        completionTime:
          format: int64
          type: integer
        debugLog:
          type: string
        embeddedRecord:
          type: string
        id:
          type: string
        startTime:
          format: int64
          type: integer
        status:
          $ref: '#/components/schemas/TaskStatus'
    TaskStatus:
      enum:
      - DEPENDENCY_FAILED
      - DOING
      - FAILED
      - IDLE
      - SUCCEEDED
      type: string
