---
openapi: 3.0.3
info:
  title: task-manager API
  version: 0.2.0-SNAPSHOT
paths:
  /:
    post:
      tags:
      - CDI Wrapper
      parameters:
      - name: ce-function
        in: header
        schema:
          type: string
      - name: ce-id
        in: header
        schema:
          type: string
      - name: ce-tasktype
        in: header
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OaasTask'
      responses:
        "201":
          description: Created
  /api/task-completions:
    post:
      tags:
      - Task Completion Consumer
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/TaskCompletion'
      responses:
        "201":
          description: Created
  /api/task-exec:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskExecRequest'
      responses:
        "201":
          description: Created
  /oal:
    post:
      tags:
      - Oal Resource
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectAccessLangauge'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasObject'
  /oal/-/{filePath}:
    post:
      tags:
      - Oal Resource
      parameters:
      - name: filePath
        in: path
        required: true
        schema:
          pattern: .*
          type: string
      - name: await
        in: query
        schema:
          type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ObjectAccessLangauge'
      responses:
        "200":
          description: OK
          content:
            application/json: {}
  /oal/{oae}:
    get:
      tags:
      - Oal Resource
      parameters:
      - name: oae
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasObject'
  /oal/{oae}/{filePath}:
    get:
      tags:
      - Oal Resource
      parameters:
      - name: filePath
        in: path
        required: true
        schema:
          pattern: .*
          type: string
      - name: oae
        in: path
        required: true
        schema:
          type: string
      - name: await
        in: query
        schema:
          type: boolean
      responses:
        "200":
          description: OK
          content:
            application/json: {}
components:
  schemas:
    OaasCompoundMember:
      type: object
      properties:
        name:
          type: string
        object:
          $ref: '#/components/schemas/UUID'
    OaasObject:
      type: object
      properties:
        access:
          $ref: '#/components/schemas/ObjectAccessModifier'
        cls:
          type: string
        embeddedRecord:
          type: string
        id:
          $ref: '#/components/schemas/UUID'
        labels:
          uniqueItems: true
          type: array
          items:
            type: string
        members:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/OaasCompoundMember'
        origin:
          $ref: '#/components/schemas/OaasObjectOrigin'
        originHash:
          format: int64
          type: integer
        state:
          $ref: '#/components/schemas/OaasObjectState'
    OaasObjectOrigin:
      type: object
      properties:
        args:
          type: object
          additionalProperties:
            type: string
        funcName:
          type: string
        inputs:
          type: array
          items:
            format: uuid
            pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
            type: string
        parentId:
          $ref: '#/components/schemas/UUID'
        rootId:
          $ref: '#/components/schemas/UUID'
    OaasObjectState:
      type: object
      properties:
        baseUrl:
          type: string
        keys:
          type: array
          items:
            type: string
        overrideUrls:
          type: object
          additionalProperties:
            type: string
        type:
          $ref: '#/components/schemas/StateType'
    OaasTask:
      type: object
      properties:
        allocOutputUrl:
          type: string
        id:
          type: string
        inputKeys:
          type: array
          items:
            type: object
            additionalProperties:
              type: string
        inputs:
          type: array
          items:
            $ref: '#/components/schemas/OaasObject'
        main:
          $ref: '#/components/schemas/OaasObject'
        mainKeys:
          type: object
          additionalProperties:
            type: string
        output:
          $ref: '#/components/schemas/OaasObject'
    ObjectAccessLangauge:
      type: object
      properties:
        args:
          type: object
          additionalProperties:
            type: string
        functionName:
          type: string
        inputs:
          type: array
          items:
            format: uuid
            pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
            type: string
        target:
          $ref: '#/components/schemas/UUID'
    ObjectAccessModifier:
      enum:
      - FINAL
      - INTERNAL
      - PUBLIC
      type: string
    StateType:
      enum:
      - COLLECTION
      - FILE
      - FILES
      - RECORD
      type: string
    TaskCompletion:
      type: object
      properties:
        completionTime:
          format: int64
          type: integer
        debugLog:
          type: string
        functionName:
          type: string
        id:
          type: string
        startTime:
          format: int64
          type: integer
        status:
          $ref: '#/components/schemas/TaskStatus'
    TaskExecRequest:
      type: object
      properties:
        id:
          type: string
    TaskStatus:
      enum:
      - DOING
      - FAILED
      - SUCCEEDED
      - WAITING
      type: string
    UUID:
      format: uuid
      pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
      type: string
