"%test":
  quarkus:
    console:
      color: true
    log:
      category:
        "org.hpcclab.oaas":
          level: TRACE
          min-level: TRACE
"%dev":
  quarkus:
    http:
      port: 8088
    datasource:
      devservices:
        port: 5432
    log:
      category:
        "org.hpcclab.oaas":
          level: DEBUG
  oaas:
    repo:
      createOnStart: true
      object:
        persist: false
      state:
        persist: false
      completion:
        persist: false
"%prod":
  quarkus:
    infinispan-client:
      auth-username: ${infinispan.username:}
      auth-password: ${infinispan.password:}
      server-list: ${infinispan.server:}

oaas:
  oc:
    provisionTopic: oaas-provisions
  log: INFO

quarkus:
  console:
    color: true
  http:
    access-log:
      enabled: true
      pattern: '"%r" %s %b %{RESPONSE_TIME} ms'
      exclude-pattern: /q/.*
    record-request-start-time: true
  vertx:
    prefer-native-transport: true
  swagger-ui:
    always-include: true
  smallrye-openapi:
    store-schema-directory: ../doc/oc
    enable: true
  index-dependency:
    service-interface:
      artifact-id: service-interface
      group-id: org.hpcclab.oaas
  log:
    category:
      "org.hpcclab.oaas":
        level: ${oaas.log}
  container-image:
    image: ${ci.registry.image:oaas}/object-controller${tag:}
  jib:
    base-jvm-image: eclipse-temurin:17-jre-alpine
  micrometer:
    export:
      json:
        enabled: true
        path: jsonmetrics
  native:
    resources:
      includes:
        - builtin/**
    builder-image: quay.io/quarkus/ubi-quarkus-mandrel:21.3-java17
mp:
  messaging:
    outgoing:
      provisions:
        connector: smallrye-kafka
        topic: ${oaas.oc.provisionTopic}
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
