"%test":
  quarkus:
    hibernate-orm:
      database:
        generation: drop-and-create
      log:
        sql: true
  oaas:
    oc:
      s3PrefixUrl: http://localhost:8888/bucket
"%dev":
  quarkus:
    hibernate-orm:
      database:
        generation: drop-and-create
      log:
        sql: true
    http:
      port: 8088
    datasource:
      devservices:
        port: 5432
  oaas:
    oc:
      s3PrefixUrl: http://localhost:8888/bucket


quarkus:
  console:
    color: true
  http:
    access-log:
      enabled: true
  vertx:
    prefer-native-transport: true
  swagger-ui:
    always-include: true
  smallrye-openapi:
    store-schema-directory: ../doc/oc

    enable: true
  index-dependency:
    service-interface:
      artifact-id: service-interface
      group-id: org.hpcclab.msc
  log:
    category:
      "org.hpcclab.msc":
        level: DEBUG
  container-image:
    image: ${ci.registry.image:oaas}/object-controller${tag:}
  jib:
    base-jvm-image: eclipse-temurin:17-alpine
  datasource:
    db-kind: postgresql
