"%test":
  quarkus:
    log:
      console:
        color: true
"%dev":
  quarkus:
    log:
      console:
        color: true
    mongodb:
      devservices:
        port: 27017
    http:
      port: 8088

quarkus:
  http:
    access-log:
      enabled: true
  mongodb:
    devservices:
      image-name: mongo:5
    database: msc-object
  vertx:
    prefer-native-transport: true
  swagger-ui:
    always-include: true
  smallrye-openapi:
    store-schema-directory: ../doc/oc
  index-dependency:
    service-interface:
      artifact-id: service-interface
      group-id: org.hpcclab.msc

  container-image:
    image: ${$ci.registry.image:oaas}${tag:}
  jib:
    base-jvm-image: adoptopenjdk/openjdk16:ubi-minimal-jre
