"%test":
  quarkus:
    console:
      color: true
    hibernate-orm:
      database:
        generation: drop-and-create
    #      log:
    #        sql: true
    log:
      category:
        "org.hpcclab.oaas":
          level: DEBUG
  oaas:
    oc:
      s3PrefixUrl: http://localhost:8888/bucket
"%dev":
  quarkus:
    hibernate-orm:
      database:
        generation: drop-and-create
      log:
        sql: true
    http:
      port: 8088
    datasource:
      devservices:
        port: 5432
    log:
      category:
        "org.hpcclab.oaas":
          level: DEBUG

oaas:
  oc:
    s3PrefixUrl: http://localhost:8888/bucket
    provisionTopic: oaas-provisions

quarkus:
  console:
    color: true
  hibernate-orm:
    database:
#      generation: create
      generation: update
  http:
    access-log:
      enabled: true
      pattern: '%h %t "%r" %s %b %{RESPONSE_TIME} ms'
    record-request-start-time: true
  vertx:
    prefer-native-transport: true
  swagger-ui:
    always-include: true
  smallrye-openapi:
    store-schema-directory: ../doc/oc
    enable: true
  index-dependency:
    service-interface:
      artifact-id: service-interface
      group-id: org.hpcclab.msc
  #  log:
  #    category:
  #      "org.hpcclab.oaas":
  #        level: DEBUG
  container-image:
    image: ${ci.registry.image:oaas}/object-controller${tag:}
  jib:
    base-jvm-image: eclipse-temurin:17-alpine
  datasource:
    db-kind: postgresql
  micrometer:
    export:
      json:
        enabled: true
        path: jsonmetrics
  native:
    resources:
      includes:
        - builtin/**
    builder-image: quay.io/quarkus/ubi-quarkus-mandrel:21.3-java17

mp:
  messaging:
    outgoing:
      provisions:
        connector: smallrye-kafka
        topic: ${oaas.oc.provisionTopic}
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
