"%test":
  quarkus:
    console:
      color: true
    log:
      min-level: TRACE
  oaas:
    log: TRACE

"%dev":
  quarkus:
    http:
      port: 8088
    datasource:
      devservices:
        port: 5432
  oaas:
    log: DEBUG

"%prod":
#  quarkus:
#    infinispan-client:
#      auth-username: ${infinispan.username:}
#      auth-password: ${infinispan.password:}
#      server-list: ${infinispan.server:}
  oaas:
    oc:
      kafkaEnabled: true

oaas:
  oc:
    storageAdapterUrl: http://localhost:8093
    provisionTopic: oaas-provisions
    kafkaEnabled: false
  log: INFO

quarkus:
  console:
    color: true
  http:
    access-log:
      enabled: true
      pattern: '"%r" %s %b %{RESPONSE_TIME} ms'
      exclude-pattern: /q/.*
    record-request-start-time: true
  vertx:
    prefer-native-transport: true
  swagger-ui:
    always-include: true
  smallrye-openapi:
    store-schema-directory: ../doc/oc
    enable: true
  log:
    category:
      "org.hpcclab.oaas":
        level: ${oaas.log}
  container-image:
    image: ${ci.registry.image:oaas}/object-controller${tag:}
  jib:
    base-jvm-image: eclipse-temurin:17-jre-alpine
  micrometer:
    export:
      json:
        enabled: true
        path: jsonmetrics
  native:
    resources:
      includes:
        - builtin/**
    builder-image: quay.io/quarkus/ubi-quarkus-mandrel:22.2-java17
  opentelemetry:
    enabled: false
  rest-client:
    allocation-api:
      url: ${oaas.oc.storageAdapterUrl}
  kafka:
    devservices:
      enabled: false
mp:
  messaging:
    outgoing:
      provisions:
        enabled: ${oaas.oc.kafkaEnabled}
        connector: smallrye-kafka
        topic: ${oaas.oc.provisionTopic}
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
