"%test":
  quarkus:
    console:
      color: true
    log:
      category:
        "org.hpcclab.oaas":
          level: TRACE
          min-level: TRACE
  oaas:
    oc:
      s3PrefixUrl: http://localhost:8888/bucket
"%dev":
  quarkus:
    http:
      port: 8088
    datasource:
      devservices:
        port: 5432
    log:
      category:
        "org.hpcclab.oaas":
          level: DEBUG
"%prod":
  quarkus:
    infinispan-client:
      auth-username: ${infinispan.username:}
      auth-password: ${infinispan.password:}
      server-list: ${infinispan.server:}

oaas:
  oc:
    s3PrefixUrl: http://localhost:8888/bucket
    provisionTopic: oaas-provisions
quarkus:
  console:
    color: true
  http:
    access-log:
      enabled: true
      pattern: '%h %t "%r" %s %b %{RESPONSE_TIME} ms'
    record-request-start-time: true
  vertx:
    prefer-native-transport: true
  swagger-ui:
    always-include: true
  smallrye-openapi:
    store-schema-directory: ../doc/oc
    enable: true
  index-dependency:
    service-interface:
      artifact-id: service-interface
      group-id: org.hpcclab.oaas
  #  log:
  #    category:
  #      "org.hpcclab.oaas":
  #        level: DEBUG
  container-image:
    image: ${ci.registry.image:oaas}/object-controller${tag:}
  jib:
    base-jvm-image: eclipse-temurin:17-jre-alpine
  micrometer:
    export:
      json:
        enabled: true
        path: jsonmetrics
  native:
    resources:
      includes:
        - builtin/**
    builder-image: quay.io/quarkus/ubi-quarkus-mandrel:21.3-java17
  infinispan-client:
    near-cache-max-entries: 1000
mp:
  messaging:
    outgoing:
      provisions:
        connector: smallrye-kafka
        topic: ${oaas.oc.provisionTopic}
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
