apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: oaas-object
spec:
  clusterName: oaas-infinispan
  name: OaasObject
  template: |
    distributedCache:
      encoding:
        key:
          mediaType: application/x-protostream
        value:
          mediaType: application/x-protostream
      indexing:
        enabled: "true"
        indexedEntities:
        - oaas.OaasObject
      locking:
        acquireTimeout: "15000"
        concurrencyLevel: "1000"
        striping: "false"
      memory:
        maxSize: "256000000"
        storage: OFF_HEAP
      mode: SYNC
      partitionHandling:
        mergePolicy: PREFERRED_NON_NULL
        whenSplit: ALLOW_READ_WRITES
      persistence:
        passivation: "false"
        rocksdbStore:
          fetchState: "true"
          writeBehind:
            modificationQueueSize: "8192"
      remoteTimeout: "17500"
      stateTransfer:
        timeout: "300000"
      statistics: "true"
