apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: knative-group
  bootstrapServers:
    - msc-kafka-bootstrap.msc:9092
  topics:
    - msc-tasks
  sink:
    ref:
      kind: Broker
      apiVersion: eventing.knative.dev/v1
      name: default
