
"%dev":
  quarkus:
    http:
      port: 8091
    log:
      category:
        "org.hpcclab.oaas":
          level: DEBUG

oaas:
  kp:
    provisionTopic: oaas-provisions
    taskCompletionTopic: oaas-task-completions
    exposeKnative: false

quarkus:
  http:
    access-log:
      enabled: true
  vertx:
    prefer-native-transport: true
  container-image:
    image: ${ci.registry.image:oaas}/kube-provisioner${tag:}
  jib:
    base-jvm-image: eclipse-temurin:17-jre-alpine
  console:
    color: true
  native:
    builder-image: quay.io/quarkus/ubi-quarkus-mandrel:21.3-java17
#  log:
#    category:
#      "org.hpcclab.oaas":
#        level: DEBUG
mp:
  messaging:
    incoming:
      provisions:
        connector: smallrye-kafka
        topic: ${oaas.kp.provisionTopic}
        auto:
          offset:
            reset: earliest
    outgoing:
      task-completions:
        merge: true
        connector: smallrye-kafka
        topic: ${oaas.kp.taskCompletionTopic}
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
        cloud-events-source: ${quarkus.application.name}
        cloud-events-type: oaas.task-completion
