
"%dev":
  quarkus:
    http:
      port: 8091
    log:
      category:
        "org.hpcclab.oaas":
          level: DEBUG

oaas:
  kp:
    provisionTopic: oaas-provisions
    exposeKnative: false

quarkus:
  http:
    access-log:
      enabled: true
      exclude-pattern: /q/.*
  vertx:
    prefer-native-transport: true
  container-image:
    image: ${ci.registry.image:oaas}/kube-provisioner${tag:}
  jib:
    base-jvm-image: eclipse-temurin:17-jre-alpine
  console:
    color: true
  native:
    builder-image: quay.io/quarkus/ubi-quarkus-mandrel:21.3-java17
mp:
  messaging:
    incoming:
      provisions:
        connector: smallrye-kafka
        topic: ${oaas.kp.provisionTopic}
        auto:
          offset:
            reset: earliest
