apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-delivery-service
  labels:
    app: content-delivery-service
  namespace: msc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-delivery-service
  template:
    metadata:
      labels:
        app: content-delivery-service
    spec:
      containers:
        - name: content-delivery-service
          image: core.harbor.10.131.36.27.nip.io/msc/content-delivery-service:latest
          ports:
            - containerPort: 80
          imagePullPolicy: Always
          env:
            - name: redis_host
              value: redis-master.msc.svc.cluster.local
            - name: redis_port
              value: '6379'
            - name: sleep
              value: '0.3'
            - name: redis_connection_pool
              value: '100'
            - name: resolver
              value: local=on
            - name: resource_request_queue_host
              value: task-manager.msc.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: content-delivery-service
  namespace: msc
spec:
  selector:
    app: content-delivery-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

