apiVersion: infinispan.org/v1
kind: Infinispan
metadata:
  name: oaas-infinispan
spec:
  image: quay.io/infinispan/server:13.0.8.Final
#  image: quay.io/infinispan/server:14.0
  replicas: 3
  service:
    type: DataGrid
    container:
      storage: 5Gi
  security:
    endpointSecretName: infinispan-connect-secret
  container:
    cpu: "16:2"
    memory: "6Gi:2Gi"
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app: infinispan-pod
                clusterName: oaas-infinispan
                infinispan_cr: oaas-infinispan
            topologyKey: "kubernetes.io/hostname"
---
