apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-provisioner
  labels:
    app: job-provisioner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-provisioner
  template:
    metadata:
      labels:
        app: job-provisioner
    spec:
      serviceAccountName: jp-sa
      containers:
        - name: job-provisioner
          envFrom:
            - configMapRef:
                name: oaas-env
          image: registry.gitlab.com/multimedia-streaming-cloud-ecosystem/msc-oaas/job-provisioner
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512M
            requests:
              cpu: 500m
              memory: 256M
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: job-provisioner
spec:
  selector:
    app: job-provisioner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
