---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kp-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kp-role
rules:
  - apiGroups: ["serving.knative.dev"]
    resources: ["services"]
    verbs: ["*"]
  - apiGroups: ["flows.knative.dev"]
    resources: ["sequences"]
    verbs: ["*"]
  - apiGroups: ["eventing.knative.dev"]
    resources: ["triggers"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kp-rb
roleRef:
  kind: Role
  name: kp-role
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: kp-sa
