apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: kube-provisioner-trigger
  annotations:
    knative-eventing-injection: enabled
spec:
  broker: default
  filter:
    attributes:
#      kafkaheadercetasktype: EPHEMERAL
#      kafkaheadercetype: oaas.task
      tasktype: EPHEMERAL
      type: oaas.task
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: kube-provisioner
