resources:
  - env-configmap.yaml
  # job-provisioner
  - kp.yml
  - kp-rb.yml
  - kp-trigger.yml
  # task-generator
  - tm.yml
  # object-controller
  - oc-postgres.yml
  - oc.yml
  # task-completion-handler
  - tch.yml
  # CDN
  - cdn.yml
#  - monitor.yml
