apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: oc-monitor
spec:
  endpoints:
    - interval: 10s
      path: /q/metrics
      targetPort: http
  namespaceSelector:
    matchNames:
      - msc
  selector:
    matchLabels:
      app: object-controller
