apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oc-postgres
  name: oc-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oc-postgres
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: oc-postgres
    spec:
      containers:
        - image: postgres
          env:
            - name: POSTGRES_USER
              value: oaas
            - name: POSTGRES_PASSWORD
              value: oaas
            - name: POSTGRES_DB
              value: oaas
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          name: oc-postgres
          ports:
            - containerPort: 5432
          resources:
            limits:
              memory: 2G
            requests:
              cpu: 500m
              memory: 256M
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: oc-postgres-pvc
      restartPolicy: Always
      volumes:
        - name: oc-postgres-pvc
          persistentVolumeClaim:
            claimName: oc-postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: oc-postgres
  name: oc-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5G
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oc-postgres
  name: oc-postgres
spec:
  ports:
    - name: "postgres"
      port: 5432
      targetPort: 5432
  selector:
    app: oc-postgres
