apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-controller
  labels:
    app: object-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-controller
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app: object-controller
    spec:
      containers:
        - name: object-controller
          envFrom:
            - configMapRef:
                name: oaas-env
            - configMapRef:
                name: msc-bucket
          env:
            - name: QUARKUS_MONGODB_CONNECTION_STRING
              value: mongodb://oc-mongo:27017
            - name: QUARKUS_MONGODB_DATABASE
              value: object-controller
            - name: OAAS_OC_S3PREFIXURL
              value: 'http://${BUCKET_HOST}/${BUCKET_NAME}'
          image: registry.gitlab.com/multimedia-streaming-cloud-ecosystem/msc-oaas/object-controller:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512M
            requests:
              cpu: 500m
              memory: 256M
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: object-controller
spec:
  selector:
    app: object-controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
