apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-controller
  labels:
    app: object-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-controller
  template:
    metadata:
      labels:
        app: object-controller
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: object-controller
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: object-controller
          envFrom:
            - configMapRef:
                name: oaas-env
            - configMapRef:
                name: msc-bucket
          env:
            - name: OAAS_SA_S3PREFIXURL
              value: 'http://${BUCKET_HOST}.cluster.local/${BUCKET_NAME}'
          image: registry.gitlab.com/multimedia-streaming-cloud-ecosystem/msc-oaas/object-controller:latest
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              memory: 1G
              cpu: '2'
            requests:
              cpu: '0.1'
              memory: 256M
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: object-controller
  labels:
    app: object-controller
spec:
  selector:
    app: object-controller
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  topologyKeys:
    - "kubernetes.io/hostname"
    - "*"
