apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-adapter
  labels:
    app: storage-adapter
    platform: oaas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-adapter
      platform: oaas
  template:
    metadata:
      labels:
        app: storage-adapter
        platform: oaas
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: storage-adapter
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: storage-adapter
          envFrom:
            - configMapRef:
                name: oaas-env
            - configMapRef:
                name: oaas-bucket
          env:
            - name: OAAS_SA_S3_URL
              value: 'http://${BUCKET_HOST}.cluster.local'
            - name: OAAS_SA_S3_PUBLICURL
              value: 'http://${BUCKET_HOST}.cluster.local' # change here.
            - name: OAAS_SA_S3_BUCKET
              value: '${BUCKET_NAME}'
            - name: OAAS_SA_S3_ACCESSKEY
              valueFrom:
                secretKeyRef:
                  key: AWS_ACCESS_KEY_ID
                  name: oaas-bucket
            - name: OAAS_SA_S3_SECRETKEY
              valueFrom:
                secretKeyRef:
                  key: AWS_SECRET_ACCESS_KEY
                  name: oaas-bucket
          image: ghcr.io/hpcclab/oaas/storage-adapter:latest
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              memory: 2G
#              cpu: '16'
            requests:
              cpu: '0.1'
              memory: 256M
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: storage-adapter
  labels:
    app: storage-adapter
  annotations:
    service.kubernetes.io/topology-aware-hints: auto
spec:
  selector:
    app: storage-adapter
    platform: oaas
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
