apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: task-completion-handler
  labels:
    app: task-completion-handler
spec:
  template:
    metadata:
      labels:
        app: task-completion-handler
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - name: task-completion-handler
          envFrom:
            - configMapRef:
                name: oaas-env
          image: registry.gitlab.com/multimedia-streaming-cloud-ecosystem/msc-oaas/task-completion-handler
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 1G
              cpu: '4'
            requests:
              cpu: '0.5'
              memory: 256M
          imagePullPolicy: Always
#          livenessProbe:
#            failureThreshold: 3
#            httpGet:
#              path: /q/health/live
#              scheme: HTTP
#            initialDelaySeconds: 5
#            periodSeconds: 30
#            successThreshold: 1
#            timeoutSeconds: 10
#          readinessProbe:
#            failureThreshold: 10
#            httpGet:
#              path: /q/health/ready
#              scheme: HTTP
#            initialDelaySeconds: 10
#            periodSeconds: 10
#            successThreshold: 1
#            timeoutSeconds: 10
