apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-completion-handler
  labels:
    app: task-completion-handler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-completion-handler
  template:
    metadata:
      labels:
        app: task-completion-handler
    spec:
      containers:
        - name: task-completion-handler
          envFrom:
            - configMapRef:
                name: oaas-env
          image: registry.gitlab.com/multimedia-streaming-cloud-ecosystem/msc-oaas/task-completion-handler
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512M
            requests:
              cpu: 500m
              memory: 256M
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: task-completion-handler
spec:
  selector:
    app: task-completion-handler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
