apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-generator
  labels:
    app: task-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-generator
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app: task-generator
    spec:
#      initContainers:
#        - name: stream-controller
#          envFrom:
#              - configMapRef:
#                  name: oaas-env
#          image: registry.gitlab.com/multimedia-streaming-cloud-ecosystem/msc-oaas/stream-controller:latest
      containers:
        - name: task-generator
          envFrom:
            - configMapRef:
                name: oaas-env
          env:
            - name: QUARKUS_MONGODB_CONNECTION_STRING
              value: mongodb://oc-mongo:27017
            - name: QUARKUS_MONGODB_DATABASE
              value: task-generator
          image: registry.gitlab.com/multimedia-streaming-cloud-ecosystem/msc-oaas/task-generator
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512M
            requests:
              cpu: 500m
              memory: 256M
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: task-generator
spec:
  selector:
    app: task-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
