apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-manager
  labels:
    app: task-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-manager
  template:
    metadata:
      labels:
        app: task-manager
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: task-manager
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: task-manager
          envFrom:
            - configMapRef:
                name: oaas-env
            - configMapRef:
                name: msc-bucket
          env:
            - name: OAAS_SA_S3PREFIXURL
              value: 'http://${BUCKET_HOST}.cluster.local/${BUCKET_NAME}'
          image: registry.gitlab.com/multimedia-streaming-cloud-ecosystem/msc-oaas/task-manager
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 1G
              cpu: '8'
            requests:
              cpu: '0.5'
              memory: 256M
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: task-manager
spec:
  selector:
    app: task-manager
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
