apiVersion: apps/v1
kind: Deployment
metadata:
  name: object-controller
  labels:
    app: object-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: object-controller
  template:
    metadata:
      labels:
        app: object-controller
    spec:
      containers:
        - name: object-controller
          env:
            - name: JAVA_OPTIONS
              value: -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:MaxDirectMemorySize=512m
            - name: QUARKUS_MONGODB_CONNECTION_STRING
              value: mongodb://oc-mongo:27017
            - name: QUARKUS_MONGODB_DATABASE
              value: object-controller
            - name: QUARKUS_SWAGGER_UI_ALWAYS_INCLUDE
              value: "true"
          image: registry.gitlab.com/multimedia-streaming-cloud-ecosystem/msc-object-controller:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512M
            requests:
              cpu: 500m
              memory: 256M
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: object-controller
spec:
  selector:
    app: object-controller
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
