apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: msc
spec:
  kafka:
    template:
      pod:
        metadata:
          labels:
            cluster: oaas-kafka
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      cluster: oaas-kafka
                  topologyKey: "kubernetes.io/hostname"
    replicas: 3
    version: 3.0.0
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
#      - name: external
#        port: 9094
#        type: nodeport
#        tls: false
    resources:
      limits:
        cpu: 16
        memory: 8G
      requests:
        cpu: 2
        memory: 0.5G
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: true
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      log.message.format.version: '3.0'
      inter.broker.protocol.version: '3.0'
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: true
    resources:
      requests:
        cpu: 0.5
        memory: 256M
  entityOperator:
    topicOperator: {}
    userOperator: {}
#  cruiseControl: {}
