# Use postgres/example user/password credentials
version: '3.1'

services:

  infinispan:
    image: quay.io/infinispan/server
    restart: always
    ports:
      - "11222:11222"
    environment:
      USER: admin
      PASS: changeme


  oc:
    image: core.harbor.10.131.36.27.nip.io/oaas/object-controller
    restart: always
    ports:
      - "8088:8080"
    environment:
      QUARKUS_CONSOLE_COLOR: 'false'
      KAFKA_BOOTSTRAP_SERVERS: PLAINTEXT://redpanda:9092
      OAAS_OC_TASKGENERATORURL: http://task-manager
      OAAS_OC_PROVISIONTOPIC: msc-provisions
      OAAS_OC_S3PREFIXURL: http://s3.10.131.36.27.nip.io/test
      INFINISPAN_SERVER: infinispan:11222
      INFINISPAN_USERNAME: admin
      INFINISPAN_PASSWORD: changeme

  redpanda:
    command:
      - redpanda
      - start
      - --smp
      - '1'
      - --reserve-memory
      - 0M
      - --overprovisioned
      - --node-id
      - '0'
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    # NOTE: Please use the latest version here!
    image: docker.vectorized.io/vectorized/redpanda:v21.10.2
    container_name: redpanda-1
    ports:
      - 9092:9092
      - 29092:29092
