apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: arango-cluster
spec:
  mode: Cluster
  tls:
    caSecretName: None
  externalAccess:
    type: NodePort
    nodePort: 31234
  agents:
    count: 3
    resources:
      requests:
        storage: 8Gi
  dbservers:
    count: 3
    resources:
      requests:
        storage: 10Gi
  coordinators:
    count: 3
  image: "arangodb/arangodb:3.10.5"
