resources:
  - ../local

images:
  - name: ghcr.io/hpcclab/oaas/object-controller
    newName: oaas-oc
    newTag: latest
  - name: ghcr.io/hpcclab/oaas/kube-provisioner
    newName: oaas-kp
    newTag: latest
  - name: ghcr.io/hpcclab/oaas/storage-adapter
    newName: oaas-sa
    newTag: latest
  - name: ghcr.io/hpcclab/oaas/invoker
    newName: oaas-invoker
    newTag: latest

patches:
  - target:
      version: v1
      kind: Deployment
      name: object-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      version: v1
      kind: Deployment
      name: kube-provisioner
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      version: v1
      kind: Deployment
      name: storage-adapter
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
  - target:
      version: v1
      kind: Deployment
      name: invoker
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
