"%test":
  quarkus:
    console:
      color: true
    log:
      min-level: TRACE
  oaas:
    log: TRACE

"%dev":
  quarkus:
    http:
      port: 8088
  oaas:
    log: DEBUG


oaas:
  log: INFO
  name: invoker

quarkus:
  console:
    color: true
  http:
    access-log:
      enabled: true
      pattern: '"%r" %s %b %{RESPONSE_TIME} ms'
      exclude-pattern: /q/.*
    record-request-start-time: true
  vertx:
    prefer-native-transport: true
  log:
    category:
      "org.hpcclab.oaas":
        level: ${oaas.log}
  container-image:
    image: ${ci.registry.image:oaas}/${oaas.name}${tag:}
  jib:
    base-jvm-image: eclipse-temurin:17-jre-alpine
    jvm-arguments: -Djava.util.logging.manager=org.jboss.logmanager.LogManager
  micrometer:
    export:
      json:
        enabled: true
        path: jsonmetrics
  native:
    resources:
      includes:
        - builtin/**
    builder-image: quay.io/quarkus/ubi-quarkus-mandrel:22.3-java17
#  opentelemetry:
#    enabled: false
