
"%dev":
  quarkus:
    http:
      port: 8091

oaas:
  jp:
    taskTopic: msc-tasks
    taskCompletionTopic: msc-task-completions


quarkus:
  http:
    access-log:
      enabled: true
  vertx:
    prefer-native-transport: true
  container-image:
    image: ${ci.registry.image:oaas}/job-provisioner${tag:}
  jib:
    base-jvm-image: eclipse-temurin:17-alpine
  index-dependency:
    service-interface:
      artifact-id: model
      group-id: org.hpcclab.msc
  console:
    color: true
  log:
    category:
      "org.hpcclab.msc":
        level: DEBUG
mp:
  messaging:
    incoming:
      tasks:
        connector: smallrye-kafka
        topic: ${oaas.jp.taskTopic}
        auto:
          offset:
            reset: earliest
    outgoing:
      task-completions:
        connector: smallrye-kafka
        topic: ${oaas.jp.taskCompletionTopic}
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
        cloud-events-source: ${quarkus.application.name}
        cloud-events-type: oaas.task-completion
