---
openapi: 3.0.3
info:
  title: object-controller API
  version: 0.1.0-SNAPSHOT
paths:
  /api/classes:
    get:
      tags:
      - Class Service
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OaasClassDto'
    post:
      tags:
      - Class Service
      parameters:
      - name: update
        in: query
        schema:
          default: false
          type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OaasClassDto'
          text/x-yaml:
            schema:
              type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasClassDto'
  /api/classes/{name}:
    get:
      tags:
      - Class Service
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasClassDto'
    delete:
      tags:
      - Class Service
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasClassDto'
    patch:
      tags:
      - Class Service
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OaasClassDto'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasClassDto'
  /api/functions:
    get:
      tags:
      - Function Service
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OaasFunctionDto'
    post:
      tags:
      - Function Service
      parameters:
      - name: update
        in: query
        schema:
          default: false
          type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OaasFunctionDto'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasFunctionDto'
  /api/functions/-/yaml:
    post:
      tags:
      - Function Service
      parameters:
      - name: update
        in: query
        schema:
          default: false
          type: boolean
      requestBody:
        content:
          text/x-yaml:
            schema:
              type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OaasFunctionDto'
  /api/functions/{funcName}:
    get:
      tags:
      - Function Service
      parameters:
      - name: funcName
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasFunctionDto'
  /api/objects:
    get:
      tags:
      - Object Service
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OaasObjectDto'
    post:
      tags:
      - Object Service
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OaasObjectDto'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasObjectDto'
  /api/objects/{id}:
    get:
      tags:
      - Object Service
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasObjectDto'
  /api/objects/{id}/binds:
    post:
      tags:
      - Object Service
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/OaasFunctionBindingDto'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasObjectDto'
  /api/objects/{id}/deep:
    get:
      tags:
      - Object Service
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeepOaasObjectDto'
  /api/objects/{id}/exec:
    post:
      tags:
      - Object Service
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FunctionCallRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasObjectDto'
  /api/objects/{id}/r-exec:
    post:
      tags:
      - Object Service
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FunctionCallRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasObjectDto'
components:
  schemas:
    AccessModifier:
      enum:
      - INTERNAL
      - PRIVATE
      - PUBLIC
      type: string
    AccessModifier1:
      enum:
      - FINAL
      - INTERNAL
      - PUBLIC
      type: string
    DeepOaasObjectDto:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        origin:
          $ref: '#/components/schemas/OaasObjectOrigin'
        originHash:
          format: int64
          type: integer
        type:
          $ref: '#/components/schemas/ObjectType'
        access:
          $ref: '#/components/schemas/AccessModifier1'
        classes:
          type: array
          items:
            $ref: '#/components/schemas/OaasClassDto'
        labels:
          type: object
          additionalProperties:
            type: string
        functions:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/OaasFunctionDto'
        state:
          $ref: '#/components/schemas/OaasObjectState'
        members:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/OaasCompoundMemberDto'
    FuncType:
      enum:
      - LOGICAL
      - MACRO
      - TASK
      type: string
    FunctionCallRequest:
      required:
      - functionName
      type: object
      properties:
        target:
          $ref: '#/components/schemas/UUID'
        functionName:
          pattern: \S
          type: string
          nullable: false
        args:
          type: object
          additionalProperties:
            type: string
        additionalInputs:
          type: array
          items:
            format: uuid
            pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
            type: string
    OaasClassDto:
      type: object
      properties:
        name:
          type: string
        objectType:
          $ref: '#/components/schemas/ObjectType'
        stateType:
          $ref: '#/components/schemas/StateType'
        functions:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/OaasFunctionBindingDto'
    OaasCompoundMemberDto:
      type: object
      properties:
        name:
          type: string
        object:
          $ref: '#/components/schemas/OaasObjectDto'
    OaasFunctionBindingDto:
      type: object
      properties:
        access:
          $ref: '#/components/schemas/AccessModifier'
        function:
          type: string
    OaasFunctionDto:
      required:
      - name
      - type
      type: object
      properties:
        name:
          pattern: \S
          type: string
          nullable: false
        type:
          allOf:
          - $ref: '#/components/schemas/FuncType'
          - nullable: false
        outputClasses:
          type: array
          items:
            type: string
        validation:
          $ref: '#/components/schemas/OaasFunctionValidation'
        task:
          $ref: '#/components/schemas/TaskConfiguration'
        macro:
          $ref: '#/components/schemas/OaasWorkflow'
    OaasFunctionValidation:
      type: object
      properties:
        bindingRequirement:
          $ref: '#/components/schemas/OaasObjectRequirement'
        additionalInputs:
          type: array
          items:
            $ref: '#/components/schemas/OaasObjectRequirement'
    OaasObjectDto:
      type: object
      properties:
        id:
          $ref: '#/components/schemas/UUID'
        origin:
          $ref: '#/components/schemas/OaasObjectOrigin'
        originHash:
          format: int64
          type: integer
        type:
          $ref: '#/components/schemas/ObjectType'
        access:
          $ref: '#/components/schemas/AccessModifier1'
        classes:
          type: array
          items:
            type: string
        labels:
          type: object
          additionalProperties:
            type: string
        functions:
          type: array
          items:
            $ref: '#/components/schemas/OaasFunctionDto'
        state:
          $ref: '#/components/schemas/OaasObjectState'
        members:
          type: array
          items:
            $ref: '#/components/schemas/OaasCompoundMemberDto'
    OaasObjectOrigin:
      type: object
      properties:
        rootId:
          $ref: '#/components/schemas/UUID'
        parentId:
          $ref: '#/components/schemas/UUID'
        funcName:
          type: string
        args:
          type: object
          additionalProperties:
            type: string
        additionalInputs:
          type: array
          items:
            format: uuid
            pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
            type: string
    OaasObjectRequirement:
      type: object
      properties:
        requiredLabels:
          type: object
          additionalProperties:
            type: string
        requiredType:
          $ref: '#/components/schemas/ObjectType'
        requiredStateType:
          type: string
    OaasObjectState:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/StateType'
        baseUrl:
          type: string
        file:
          type: string
        files:
          type: array
          items:
            type: string
        records:
          type: string
    OaasWorkflow:
      type: object
      properties:
        steps:
          type: array
          items:
            $ref: '#/components/schemas/OaasWorkflowStep'
        exports:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/OaasWorkflowExport'
    OaasWorkflowExport:
      type: object
      properties:
        from:
          type: string
        as:
          type: string
    OaasWorkflowStep:
      type: object
      properties:
        funcName:
          type: string
        target:
          type: string
        as:
          type: string
        inputRefs:
          type: array
          items:
            type: string
    ObjectType:
      enum:
      - COMPOUND
      - RESOURCE
      type: string
    StateType:
      enum:
      - FILE
      - FILES
      - RECORD
      - SEGMENTABLE
      type: string
    TaskConfiguration:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/Type'
        image:
          type: string
        commands:
          type: array
          items:
            type: string
        containerArgs:
          type: array
          items:
            type: string
        argsToEnv:
          type: boolean
    Type:
      enum:
      - DURABLE
      - EPHEMERAL
      - LOGICAL
      type: string
    UUID:
      format: uuid
      pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
      type: string
