---
openapi: 3.0.3
info:
  title: object-controller API
  version: 0.1.0
paths:
  /api/batch:
    post:
      tags:
      - Batch Service
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Batch'
          text/x-yaml:
            schema:
              type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Batch'
  /api/classes:
    get:
      tags:
      - Class Service
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OaasClassDto'
    post:
      tags:
      - Class Service
      parameters:
      - name: update
        in: query
        schema:
          default: false
          type: boolean
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OaasClassDto'
          text/x-yaml:
            schema:
              type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasClassDto'
  /api/classes/{name}:
    get:
      tags:
      - Class Service
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasClassDto'
    delete:
      tags:
      - Class Service
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasClassDto'
    patch:
      tags:
      - Class Service
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OaasClassDto'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasClassDto'
  /api/functions:
    get:
      tags:
      - Function Service
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OaasFunctionDto'
    post:
      tags:
      - Function Service
      parameters:
      - name: update
        in: query
        schema:
          default: false
          type: boolean
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/OaasFunctionDto'
          text/x-yaml:
            schema:
              type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OaasFunctionDto'
  /api/functions/{funcName}:
    get:
      tags:
      - Function Service
      parameters:
      - name: funcName
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasFunctionDto'
  /api/objects:
    get:
      tags:
      - Object Service
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OaasObjectDto'
    post:
      tags:
      - Object Service
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OaasObjectDto'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasObjectDto'
  /api/objects/{id}:
    get:
      tags:
      - Object Service
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasObjectDto'
  /api/objects/{id}/binds:
    post:
      tags:
      - Object Service
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/OaasFunctionBindingDto'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasObjectDto'
  /api/objects/{id}/context:
    get:
      tags:
      - Object Service
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaskContext'
  /api/objects/{id}/deep:
    get:
      tags:
      - Object Service
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeepOaasObjectDto'
  /api/objects/{id}/exec:
    post:
      tags:
      - Object Service
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FunctionCallRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasObjectDto'
  /api/objects/{id}/origin:
    get:
      tags:
      - Object Service
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      - name: deep
        in: query
        schema:
          format: int32
          default: "1"
          type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  additionalProperties:
                    $ref: '#/components/schemas/OaasObjectOrigin'
  /api/objects/{id}/r-exec:
    post:
      tags:
      - Object Service
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FunctionCallRequest'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OaasObjectDto'
components:
  schemas:
    AccessModifier:
      enum:
      - FINAL
      - INTERNAL
      - PUBLIC
      type: string
    AccessModifier1:
      enum:
      - INTERNAL
      - PRIVATE
      - PUBLIC
      type: string
    Batch:
      type: object
      properties:
        classes:
          type: array
          items:
            $ref: '#/components/schemas/OaasClassDto'
        functions:
          type: array
          items:
            $ref: '#/components/schemas/OaasFunctionDto'
    DeepOaasClassDto:
      type: object
      properties:
        functions:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/DeepOaasFunctionBindingDto'
        name:
          type: string
        objectType:
          $ref: '#/components/schemas/ObjectType'
        stateType:
          $ref: '#/components/schemas/StateType'
    DeepOaasFunctionBindingDto:
      type: object
      properties:
        access:
          $ref: '#/components/schemas/AccessModifier1'
        function:
          $ref: '#/components/schemas/OaasFunctionDto'
    DeepOaasObjectDto:
      type: object
      properties:
        access:
          $ref: '#/components/schemas/AccessModifier'
        cls:
          $ref: '#/components/schemas/DeepOaasClassDto'
        functions:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/DeepOaasFunctionBindingDto'
        id:
          $ref: '#/components/schemas/UUID'
        labels:
          type: object
          additionalProperties:
            type: string
        members:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/OaasCompoundMemberDto'
        origin:
          $ref: '#/components/schemas/OaasObjectOrigin'
        originHash:
          format: int64
          type: integer
        state:
          $ref: '#/components/schemas/OaasObjectState'
        type:
          $ref: '#/components/schemas/ObjectType'
    FuncType:
      enum:
      - LOGICAL
      - MACRO
      - TASK
      type: string
    FunctionCallRequest:
      required:
      - functionName
      type: object
      properties:
        additionalInputs:
          type: array
          items:
            format: uuid
            pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
            type: string
        args:
          type: object
          additionalProperties:
            type: string
        functionName:
          pattern: \S
          type: string
          nullable: false
        target:
          $ref: '#/components/schemas/UUID'
    OaasClassDto:
      type: object
      properties:
        functions:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/OaasFunctionBindingDto'
        name:
          type: string
        objectType:
          $ref: '#/components/schemas/ObjectType'
        stateType:
          $ref: '#/components/schemas/StateType'
    OaasCompoundMemberDto:
      type: object
      properties:
        name:
          type: string
        object:
          $ref: '#/components/schemas/UUID'
    OaasFunctionBindingDto:
      required:
      - function
      type: object
      properties:
        access:
          $ref: '#/components/schemas/AccessModifier1'
        function:
          type: string
          nullable: false
    OaasFunctionDto:
      required:
      - name
      - type
      type: object
      properties:
        macro:
          $ref: '#/components/schemas/OaasWorkflow'
        name:
          pattern: \S
          type: string
          nullable: false
        outputCls:
          type: string
        task:
          $ref: '#/components/schemas/TaskConfiguration'
        type:
          allOf:
          - $ref: '#/components/schemas/FuncType'
          - nullable: false
        validation:
          $ref: '#/components/schemas/OaasFunctionValidation'
    OaasFunctionValidation:
      type: object
      properties:
        additionalInputs:
          type: array
          items:
            $ref: '#/components/schemas/OaasObjectRequirement'
        bindingRequirement:
          $ref: '#/components/schemas/OaasObjectRequirement'
    OaasObjectDto:
      type: object
      properties:
        access:
          $ref: '#/components/schemas/AccessModifier'
        cls:
          type: string
        functions:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/OaasFunctionBindingDto'
        id:
          $ref: '#/components/schemas/UUID'
        labels:
          type: object
          additionalProperties:
            type: string
        members:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/OaasCompoundMemberDto'
        origin:
          $ref: '#/components/schemas/OaasObjectOrigin'
        originHash:
          format: int64
          type: integer
        state:
          $ref: '#/components/schemas/OaasObjectState'
        type:
          $ref: '#/components/schemas/ObjectType'
    OaasObjectOrigin:
      type: object
      properties:
        additionalInputs:
          type: array
          items:
            format: uuid
            pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
            type: string
        args:
          type: object
          additionalProperties:
            type: string
        funcName:
          type: string
        parentId:
          $ref: '#/components/schemas/UUID'
        rootId:
          $ref: '#/components/schemas/UUID'
    OaasObjectRequirement:
      type: object
      properties:
        requiredClass:
          type: string
        requiredLabels:
          type: object
          additionalProperties:
            type: string
        requiredStateType:
          type: string
        requiredType:
          $ref: '#/components/schemas/ObjectType'
    OaasObjectState:
      type: object
      properties:
        baseUrl:
          type: string
        files:
          type: array
          items:
            type: string
        records:
          type: string
        type:
          $ref: '#/components/schemas/StateType'
    OaasWorkflow:
      type: object
      properties:
        exports:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/OaasWorkflowExport'
        steps:
          type: array
          items:
            $ref: '#/components/schemas/OaasWorkflowStep'
    OaasWorkflowExport:
      type: object
      properties:
        as:
          type: string
        from:
          type: string
    OaasWorkflowStep:
      type: object
      properties:
        as:
          type: string
        funcName:
          type: string
        inputRefs:
          type: array
          items:
            type: string
        target:
          type: string
    ObjectType:
      enum:
      - COMPOUND
      - RESOURCE
      type: string
    StateType:
      enum:
      - FILE
      - FILES
      - RECORD
      - SEGMENTABLE
      type: string
    TaskConfiguration:
      type: object
      properties:
        argsToEnv:
          type: boolean
        commands:
          type: array
          items:
            type: string
        containerArgs:
          type: array
          items:
            type: string
        image:
          type: string
        outputFileNames:
          type: array
          items:
            type: string
        provisionConfig:
          type: object
          additionalProperties:
            type: string
        type:
          $ref: '#/components/schemas/Type'
    TaskContext:
      type: object
      properties:
        additionalInputs:
          type: array
          items:
            $ref: '#/components/schemas/OaasObjectDto'
        function:
          $ref: '#/components/schemas/OaasFunctionDto'
        output:
          $ref: '#/components/schemas/OaasObjectDto'
        parent:
          $ref: '#/components/schemas/OaasObjectDto'
    Type:
      enum:
      - DURABLE
      - EPHEMERAL
      - LOGICAL
      type: string
    UUID:
      format: uuid
      pattern: "[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}"
      type: string
