
"%dev":
  quarkus:
    http:
      port: 8090

objectControllerUrl: http://localhost:8088

org:
  hpcclab:
    msc:
      object:
        service:
          FunctionService/mp-rest/url: ${objectControllerUrl}
quarkus:
  http:
    access-log:
      enabled: true
  vertx:
    prefer-native-transport: true
  swagger-ui:
    always-include: true
  smallrye-openapi:
    store-schema-directory: ../doc/tg
  index-dependency:
    service-interface:
      artifact-id: service-interface
      group-id: org.hpcclab.msc
