"%dev":
  quarkus:
    http:
      port: 8090

oaas:
  tg:
    objectControllerUrl: http://localhost:8088
    taskEventTopic: oaas-task-events
    taskTopic: oaas-tasks
    taskCompletionTopic: oaas-task-completions
    defaultTraverse: 3
    stateStoreName: task-state

quarkus:
  http:
    access-log:
      enabled: true
  vertx:
    prefer-native-transport: true
  swagger-ui:
    always-include: true
  smallrye-openapi:
    store-schema-directory: ../doc/tg
  index-dependency:
    service-interface:
      artifact-id: service-interface
      group-id: org.hpcclab.msc
  console:
    color: true
  container-image:
    image: ${ci.registry.image:oaas}/task-generator${tag:}
  jib:
    base-jvm-image: eclipse-temurin:17-alpine
  log:
    category:
      "org.hpcclab.oaas":
        level: DEBUG
  kafka-streams:
    bootstrap-servers: ${kafka.bootstrap.servers}
    application-server: ${hostname:localhost}:${quarkus.http.port}
    topics: ${oaas.tg.taskEventTopic}

mp:
  messaging:
    outgoing:
      tasks:
        connector: smallrye-kafka
        topic: ${oaas.tg.taskTopic}
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
        cloud-events-source: ${quarkus.application.name}
        cloud-events-type: oaas.task
      task-events:
        connector: smallrye-kafka
        topic: ${oaas.tg.taskEventTopic}
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
    incoming:
      task-completions:
        connector: smallrye-kafka
        topic: ${oaas.tg.taskCompletionTopic}
        auto:
          offset:
            reset: earliest
