"%dev":
  quarkus:
    http:
      port: 8090

oaas:
  tg:
    objectControllerUrl: http://localhost:8088
    taskTopic: msc-tasks
    resourceRequestTopic: msc-resource-requests
    taskCompletionTopic: msc-task-completions

quarkus:
  http:
    access-log:
      enabled: true
  vertx:
    prefer-native-transport: true
  swagger-ui:
    always-include: true
  smallrye-openapi:
    store-schema-directory: ../doc/tg
  index-dependency:
    service-interface:
      artifact-id: service-interface
      group-id: org.hpcclab.msc
  console:
    color: true
  container-image:
    image: ${ci.registry.image:oaas}/task-generator${tag:}
  jib:
    base-jvm-image: adoptopenjdk/openjdk16:ubi-minimal-jre
  log:
    category:
      "org.hpcclab.msc":
        level: DEBUG
  mongodb:
    database: msc-task

mp:
  messaging:
    outgoing:
      tasks:
        connector: smallrye-kafka
        topic: ${oaas.tg.taskTopic}
        value:
          serializer: io.quarkus.kafka.client.serialization.ObjectMapperSerializer
    incoming:
      resource-requests:
        connector: smallrye-kafka
        topic: ${oaas.tg.resourceRequestTopic}
        auto:
          offset:
            reset: earliest
      task-completions:
        connector: smallrye-kafka
        topic: ${oaas.tg.taskCompletionTopic}
        auto:
          offset:
            reset: earliest
