apiVersion: apps/v1
kind: Deployment
metadata:
  name: artemis
  labels:
    app: artemis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: artemis
  template:
    metadata:
      labels:
        app: artemis
    spec:
      containers:
        - name: artemis
          env:
            - name: AMQ_USER
              value: "quarkus"
            - name: AMQ_PASSWORD
              value: "quarkus"
            - name: AMQ_EXTRA_ARGS
              value: "--no-autotune --mapped --no-fsync"
          image: quay.io/artemiscloud/activemq-artemis-broker:0.1.4
          ports:
            - containerPort: 8161
              protocol: TCP
              name: web
            - containerPort: 61616
              name: all
            - containerPort: 5672
              name: amqp
---
apiVersion: v1
kind: Service
metadata:
  name: artemis
spec:
  selector:
    app: artemis
  ports:
    - protocol: TCP
      port: 8161
      targetPort: 8161
      name: web
    - protocol: TCP
      port: 61616
      targetPort: 61616
      name: all
    - protocol: TCP
      port: 5672
      targetPort: 5672
      name: amqp
