apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-generator
  labels:
    app: task-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-generator
  template:
    metadata:
      labels:
        app: task-generator
    spec:
      containers:
        - name: task-generator
          env:
            - name: JAVA_OPTIONS
              value: -Djava.util.logging.manager=org.jboss.logmanager.LogManager -XX:MaxDirectMemorySize=512m
            - name: AMQP_HOST
              value: msc-rmq
            - name: AMQP_PORT
              value: '5672'
            - name: AMQP_USERNAME
              value: 'hpcclab'
            - name: AMQP_PASSWORD
              value: 'hpcclab'
            - name: OBJECTCONTROLLERURL
              value: http://object-controller
          image: registry.gitlab.com/multimedia-streaming-cloud-ecosystem/msc-oaas/task-generator
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512M
            requests:
              cpu: 500m
              memory: 256M
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: task-generator
spec:
  selector:
    app: task-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
