apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoker
spec:
  template:
    spec:
      containers:
        - name: invoker
          env:
            - name: OAAS_INVOKER_S3_PUBLICURL
              value: http://s3.127.0.0.1.nip.io:9090
            - name: OAAS_INVOKER_S3_URL
              value: http://minio.oaas.svc.cluster.local
            - name: OAAS_INVOKER_S3_BUCKET
              value: 'oaas-bkt'
